# an Elastic IP address (EIP) and associate it with the Amazon EC2 instance
AWSTemplateFormatVersion: 2010-09-09
Description: A sample template

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0ff8a91507f77f867
      InstanceType: t2.micro
      KeyName: gacamole
      BlockDeviceMappings:
        - DeviceName: /dev/sdm
          Ebs:
            VolumeType: io1
            Iops: 200
            DeleteOnTermination: true
            VolumeSize: 20
      Tags:
        - Key: Name
          Value: MyEC2Instance
  MyEIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: 
        Ref: MyEC2Instance
      Tags:
        - Key: Name
          Value: MyEIP
